In [269]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(suppress=True, formatter={'float_kind':'{:.3f}'.format})

## Wczytanie danych z plików

In [270]:
matrix = pd.read_csv('C.csv', header=None)

n = len(matrix)
print(matrix)

a = np.array(matrix.iloc[:, :n], dtype=float) 
b = np.array(matrix.iloc[:, n], dtype=float)
a, b

    0   1   2  3   4   5
0   0   5  11  3  -2 -16
1  11   0   2 -9  -2   4
2 -12 -13   0  6 -16  17
3  19   6  -2  0  -7  18
4   3 -12   2  1   0 -13


(array([[0.000, 5.000, 11.000, 3.000, -2.000],
        [11.000, 0.000, 2.000, -9.000, -2.000],
        [-12.000, -13.000, 0.000, 6.000, -16.000],
        [19.000, 6.000, -2.000, 0.000, -7.000],
        [3.000, -12.000, 2.000, 1.000, 0.000]]),
 array([-16.000, 4.000, 17.000, 18.000, -13.000]))

## Pivot wierszy

In [271]:
def pivot_matrix(a, k):
    max_indc = int()
    max = a[0, k]
    for i, el in enumerate(a[:, k]):
        if np.abs(el) > max:
            max_indc = i
            max = el
    bufor = np.copy(a[k, :])
    a[k, :] = a[max_indc, :]
    a[max_indc, :] = bufor
    return a 

## Zbadanie niezależności wierszy

In [272]:
def check_independence(a):
    print('rząd macierzy:', np.linalg.matrix_rank(a), 'wymiar:', a.shape[0])
    if np.linalg.matrix_rank(a) < a.shape[0]:
        return True
    else:
        return False
    
if check_independence(a):
    print('w macierzy znajdują się wiersze liniowo zależne ')

rząd macierzy: 5 wymiar: 5


## Stworzenie macierzy schodkowej

In [273]:
for k in range(0, n-1):
    for i in range(k+1, n):
        if a[k,k] == 0:
            print('element zerowy na pozycji:', k, k)
            print(a)
            a = pivot_matrix(a, k)
            print('\n',a)
        ratio = a[i, k] / a[k, k]
        for j in range(k, n):
            a[i, j] -= ratio * a[k, j]
        b[i] -= ratio * b[k]
        #print(a, '\n')
        #print(b, '\n')
a, b

element zerowy na pozycji: 0 0
[[0.000 5.000 11.000 3.000 -2.000]
 [11.000 0.000 2.000 -9.000 -2.000]
 [-12.000 -13.000 0.000 6.000 -16.000]
 [19.000 6.000 -2.000 0.000 -7.000]
 [3.000 -12.000 2.000 1.000 0.000]]

 [[19.000 6.000 -2.000 0.000 -7.000]
 [11.000 0.000 2.000 -9.000 -2.000]
 [-12.000 -13.000 0.000 6.000 -16.000]
 [0.000 5.000 11.000 3.000 -2.000]
 [3.000 -12.000 2.000 1.000 0.000]]


(array([[19.000, 6.000, -2.000, 0.000, -7.000],
        [0.000, -3.474, 3.158, -9.000, 2.053],
        [0.000, 0.000, -9.636, 29.864, -25.864],
        [0.000, 0.000, 0.000, 38.222, -40.769],
        [0.000, 0.000, 0.000, -0.000, 24.425]]),
 array([-16.000, 13.263, -28.273, -8.519, -31.001]))

## Obliczenie niewiadomych 

In [274]:
x = np.zeros(n)
x[-1] = b[-1] / a[n-1,n-1]

for i in range(n - 2, -1, -1):
    x[i] = (b[i] - sum([a[i][j] * x[j] for j in range(i+1, n)])) / a[i,i]

x

array([-1.422, 0.839, 1.454, -1.577, -1.269])